# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('productId', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.DateField()),
                ('link', models.DateField()),
                ('lprice', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('hprice', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('mallName', models.DateField()),
            ],
            options={
                'db_table': 'items',
            },
        ),
    ]
