# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='searchDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='items',
            name='mallName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='items',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
