# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_auto_20171024_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='productType',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
