# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0004_blogdata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blogdata',
            table='BlogData',
        ),
    ]
