# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0005_auto_20171025_1757'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogData',
        ),
    ]
