# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0006_delete_blogdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='hprice',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='productId',
            new_name='isbn',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='lprice',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='mallName',
            new_name='publisher',
        ),
        migrations.AddField(
            model_name='items',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='pubdate',
            field=models.DateField(null=True),
        ),
    ]
