# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0007_auto_20171025_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='itemId',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='isbn',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='items',
            name='pubdate',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
