# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0008_auto_20171025_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='itemId',
            new_name='isbnId',
        ),
    ]
