# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0009_auto_20171025_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='isbn',
            field=models.CharField(max_length=40),
        ),
    ]
