# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0010_auto_20171026_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='productType',
        ),
    ]
