# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0011_remove_items_producttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='isbnId',
            new_name='isbn_id',
        ),
    ]
